"""Generates HTML and JSON reports from ClientMetrics."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from alerttriage.src.reporting.metrics import ClientMetrics
from alerttriage.src.logger import get_logger

log = get_logger(__name__)

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>AlertTriage Report – {client_id}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 2rem; background: #f8fafc; color: #1e293b; }}
    h1   {{ color: #0f172a; }}
    .card {{ background: white; border-radius: 8px; padding: 1.5rem; margin-bottom: 1rem;
             box-shadow: 0 1px 3px rgba(0,0,0,.1); }}
    table {{ width: 100%; border-collapse: collapse; }}
    th, td {{ text-align: left; padding: .5rem 1rem; border-bottom: 1px solid #e2e8f0; }}
    th {{ background: #f1f5f9; }}
    .badge {{ display: inline-block; padding: .2rem .7rem; border-radius: 9999px; font-size: .8rem; }}
    .tp {{ background: #dcfce7; color: #166534; }}
    .fp {{ background: #fee2e2; color: #991b1b; }}
  </style>
</head>
<body>
  <h1>AlertTriage Report</h1>
  <p>Client: <strong>{client_id}</strong> &nbsp;|&nbsp;
     Period: {window_start} → {window_end}</p>

  <div class="card">
    <h2>Summary</h2>
    <table>
      <tr><th>Alerts analysed</th><td>{alert_count}</td></tr>
      <tr><th>Avg confidence</th><td>{avg_confidence:.1%}</td></tr>
      <tr><th>Avg latency</th><td>{avg_latency_ms:.0f} ms</td></tr>
      <tr><th>Total cost</th><td>${total_cost:.4f}</td></tr>
      <tr><th>Avg cost / alert</th><td>${avg_cost:.4f}</td></tr>
    </table>
  </div>

  <div class="card">
    <h2>Verdict Breakdown</h2>
    <table>
      <tr><th>Verdict</th><th>Count</th></tr>
      {verdict_rows}
    </table>
  </div>

  <div class="card">
    <h2>Accuracy (based on analyst feedback)</h2>
    <table>
      <tr><th>Sample size</th><td>{sample_size}</td></tr>
      <tr><th>Overall accuracy</th><td>{accuracy:.1%}</td></tr>
      <tr><th>Precision</th><td>{precision:.1%}</td></tr>
      <tr><th>Recall</th><td>{recall:.1%}</td></tr>
      <tr><th>F1</th><td>{f1:.1%}</td></tr>
    </table>
  </div>

  <p style="color:#94a3b8;font-size:.8rem;">Generated by AlertTriage v2 on {generated_at}</p>
</body>
</html>
"""


class ReportGenerator:
    def __init__(self, output_dir: Path) -> None:
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_html(self, metrics: ClientMetrics) -> Path:
        bd = metrics.verdict_breakdown
        verdict_rows = "\n".join(
            f"<tr><td>{v}</td><td>{c}</td></tr>"
            for v, c in [
                ("True Positive", bd.true_positive),
                ("False Positive", bd.false_positive),
                ("Needs Escalation", bd.needs_escalation),
                ("Needs Investigation", bd.needs_investigation),
                ("Benign", bd.benign),
                ("Unknown", bd.unknown),
            ]
        )

        html = _HTML_TEMPLATE.format(
            client_id=metrics.client_id,
            window_start=metrics.window_start.strftime("%Y-%m-%d %H:%M UTC"),
            window_end=metrics.window_end.strftime("%Y-%m-%d %H:%M UTC"),
            alert_count=metrics.alert_count,
            avg_confidence=metrics.avg_confidence,
            avg_latency_ms=metrics.avg_latency_ms,
            total_cost=metrics.cost_summary.total_usd,
            avg_cost=metrics.cost_summary.avg_cost_per_alert,
            verdict_rows=verdict_rows,
            sample_size=metrics.accuracy.sample_size,
            accuracy=metrics.accuracy.overall_accuracy,
            precision=metrics.accuracy.precision,
            recall=metrics.accuracy.recall,
            f1=metrics.accuracy.f1,
            generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        )

        ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        path = self.output_dir / f"report_{metrics.client_id}_{ts}.html"
        path.write_text(html, encoding="utf-8")
        log.info("report_generated", path=str(path))
        return path

    def generate_json(self, metrics: ClientMetrics) -> Path:
        data: dict[str, Any] = {
            "client_id": metrics.client_id,
            "window_start": metrics.window_start.isoformat(),
            "window_end": metrics.window_end.isoformat(),
            "alert_count": metrics.alert_count,
            "avg_confidence": metrics.avg_confidence,
            "avg_latency_ms": metrics.avg_latency_ms,
            "cost": {
                "total_usd": metrics.cost_summary.total_usd,
                "avg_per_alert": metrics.cost_summary.avg_cost_per_alert,
                "by_model": metrics.cost_summary.by_model,
            },
            "verdicts": {
                "true_positive": metrics.verdict_breakdown.true_positive,
                "false_positive": metrics.verdict_breakdown.false_positive,
                "needs_escalation": metrics.verdict_breakdown.needs_escalation,
                "needs_investigation": metrics.verdict_breakdown.needs_investigation,
                "benign": metrics.verdict_breakdown.benign,
                "unknown": metrics.verdict_breakdown.unknown,
            },
            "accuracy": {
                "sample_size": metrics.accuracy.sample_size,
                "overall": metrics.accuracy.overall_accuracy,
                "precision": metrics.accuracy.precision,
                "recall": metrics.accuracy.recall,
                "f1": metrics.accuracy.f1,
            },
        }
        ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        path = self.output_dir / f"report_{metrics.client_id}_{ts}.json"
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        log.info("json_report_generated", path=str(path))
        return path
